config/routes.rb
TaskApp::Application.routes.draw do

  devise_for :users
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end
    post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'
    root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :title, presence: {message: "入力してください" },
  length: {minimum: 1,message:"短すぎます"}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title,presence: true
  scope :unfinished, -> {where(done: false)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :authentication_keys => [:login]

  attr_accessor :login


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  #load_and_authorize_resource
  def after_sign_in_path_for(resource)
    projects_url(resource)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def index
    @search = Project.search(params[:q])
    if @search.result == "null"
      @projects = Project.all
    else
      @projects = @search.result
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end
  private

  def set_project
    @project = Project.find(params[:id])
  end

  before_action :set_project, only: [:show, :edit, :update, :destroy]


  def project_params
    params[:project].permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
    render nothing: true
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end

  private

  def task_params
    params[:task].permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %>
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      ユーザ名 <strong><%= current_user.username %></strong>.
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
<body>

<%= image_tag("welcome.jpeg", :size => "300x100", :alt => "welcome")%>

<%= yield %>

<%= link_to "HOME", projects_path%>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<p>
 <%= f.label :title %><br>
 <%= f.text_field :title %><br>
 <% if @project.errors.any? %>
   <%= @project.errors.messages[:title][0] %>
 <% end %>
</p>

<p>
 <%= f.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
  <%= search_form_for @search do |f| %>
    <%= f.label :title_cont, 'タイトル' %>
    <%= f.text_field :title_cont %>
    <%= f.submit '検索する' %>
  <% end %>
 <% @projects.each do |project| %>
 <li>
    <%= link_to project.title, project_path(project.id) %> (<%=" 残りタスク数 "%><%= project.tasks.unfinished.count  %><%=" / 全てのタスク数 "%><%= project.tasks.count  %>)
     <% if current_user.username == '管理人' %>
      <%= link_to "[編集]", edit_project_path(project.id) %>
      <%= link_to "[消去]", project_path(project.id), method: :delete,data: {confirm: "本当に消しますか?"} %>
  <% end %>
 </li>
 <% end %>
</ul>
  <% if current_user.username == '管理人' %>
    <p><%= link_to "Add New", new_project_path %>
  <% end %>

app/views/projects/new.html.erb
<h1>Add New</h1>

 <%= render 'form' %>

app/views/projects/show.html.erb
<script>
$(function() {
  $("input[type=checkbox]").click(function() {
    $.post('/projects/' + $(this).data('project_id') + '/tasks/' + $(this).data('id') + '/toggle');
  });
});
</script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<h1><%= @project.title %></h1>



<ul>
  <% @project.tasks.each do | task| %>
  <li>
    <% if current_user.username == @project.title || current_user.username == '管理人' %>
    <%= check_box_tag '', '', task.done, {'data-id' => task.id, 'data-project_id' => task.project_id} %>
    <% end %>
    <%= task.title %>
    <% if current_user.username == '管理人' %>
    <%=link_to "[消去]", project_task_path(task.project_id, task.id), method: :delete,
    data: {confirm: "本当に消しますか?"}  %>
    <% end %>
  </li>
  <% end %>


  <% if current_user.username == '管理人' %>
  <%= form_for [@project, @project.tasks.build] do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
  <% end %>
  <% end %>

</ul>